### ISSUE TITLE
Протестировать требования для фичи G.1.1 Просмотр главной страницы

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/QA#10]
Требования находятся здесь: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.oevrxvwrtvo5

**Comment by KashinaOksi** [comment]
- [ ] Протестировать` требования для фичи G.1.1 Просмотр главной страницы
