### ISSUE TITLE
Протестировать дизайн для фичи G.1.1 Просмотр главной страницы

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/QA#13]
Дизайн находится здесь:
https://www.figma.com/file/OkJgqsGOL7OKB2agjVMcST/CodePET?type=design&node-id=0-1&mode=design

Протестировать в 3х разрешениях

- [ ] десктоп
- [ ] планшет
- [ ] мобилка

**Comment by KashinaOksi** [comment]
Протестировать в 3х разрешениях

- [ ]  десктоп

- [ ]  планшет

- [ ]  мобилка
