### ISSUE TITLE
Протестировать дизайн для фичи V.3.1 Авторизация по email

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/QA#15]
Дизайн находится здесь:
https://www.figma.com/file/OkJgqsGOL7OKB2agjVMcST/CodePET?type=design&node-id=0-1&mode=design

**Comment by bobkofi** [comment]
Оставил комментарии

**Comment by bobkofi** [comment]
- [ ] Протестировать дизайн для фичи V.3.1 Авторизация по email
