### ISSUE TITLE
Протестировать фичу V.3.1 Авторизация по email

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/QA#18]
Необходимо:

- [x] Составить чек-лист
- [ ] Протестировать АПИ
- [ ] Протестировать валидацию
- [ ] Протестировать функционал в 3х разрешениях
- [ ] Написать баг-репорты по результатам тестирования

**Comment by bobkofi** [comment]
- [ ] Протестировать фичу V.3.1 Авторизация по email

**Comment by bobkofi** [comment]
Оставил комментарии

**Comment by bobkofi** [comment]
- [ ] Составить чек-лист

**Comment by bobkofi** [comment]
- [ ] составить

**Comment by bobkofi** [comment]
- [ ] Протестировать АПИ [POST /api/v1/token/login/ 2024/03/22](https://app.qase.io/run/CODEPET/dashboard/15)

**Comment by bobkofi** [comment]
- [ ] Протестировать валидацию [тест-ран](https://app.qase.io/run/CODEPET/dashboard/18)
- [ ]  Протестировать функционал в 3х разрешениях [тест-ран](https://app.qase.io/run/CODEPET/dashboard/18)
- [ ] Написать баг-репорты по результатам тестирования
