### ISSUE TITLE
Протестировать фичу V.3.3 восстановление пароля

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/QA#20]
Необходимо:

- [x] Составить чек-лист
- [x] Протестировать АПИ
- [x] Протестировать валидацию
- [x] Протестировать функционал в 3х разрешениях
- [x] Написать баг-репорты по результатам тестирования

**Comment by danilastepanov** [comment]
- [ ]  Составить чек-лист АПИ
- [ ] Составить чек-лист функциональность
- [ ]  Протестировать АПИ
- [ ]  Протестировать валидацию
- [ ]  Протестировать функционал в 3х разрешениях
- [ ]  Написать баг-репорты по результатам тестирования
- [ ]  Провести ретест
