### ISSUE TITLE
Протестировать фичу LK.4.6 Редактирование проектов (АПИ)

### ISSUE THREAD

**Issue by kseniia2673** [Pet-projects-CodePET/QA#84]
Необходимо:

- [x] Составить чек-лист
- [x] Протестировать апи
- [x] Написать баг-репорты по результатам тестирования

Используя требования: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit?usp=sharing
И фигму: https://www.figma.com/file/OkJgqsGOL7OKB2agjVMcST/CodePET?type=design&node-id=68-2&mode=design&t=Ljo4yLugNibaQcex-0

**Comment by danilastepanov** [comment]
- [ ]  Составить чек-лист [чек-лист метод PUT](https://app.qase.io/project/CODEPET?previewMode=side&suite=169) / [чек-лист метод PATCH](https://app.qase.io/project/CODEPET?previewMode=side&suite=170)
- [ ]  Протестировать апи
- [ ]  Написать баг-репорты по результатам тестирования
