### ISSUE TITLE
Протестировать требования для фичи V.3.1 Авторизация по email

### ISSUE THREAD

**Issue by lvps21** [Pet-projects-CodePET/QA#9]
Требования находятся здесь: https://docs.google.com/document/d/1BJeF_fFi5o3zITS83mEWs93HuW7V__C9sm5aEcvypAs/edit#heading=h.oevrxvwrtvo5

**Comment by bobkofi** [comment]
- [ ] Протестировать требования для фичи V.3.1 Авторизация по email
